import Foundation

struct AppStrings {
    static let appName = "Flux"
    static let systemMonitor = "System Monitor"
    static let download = "Download"
    static let upload = "Upload"
    static let diskRead = "Disk Read"
    static let diskWrite = "Disk Write"
    static let diskCapacity = "Disk Free"
    static let cpuUsage = "CPU Usage"
    static let memory = "Memory"
    static let cpuTemp = "CPU Temp"
    static let rpmUnit = "RPM"
    static let menuBarMetrics = "Menu Bar Layout"
    static let launchAtLogin = "Launch at Login"
    static let launchAtLoginDescription = "Start Flux when you sign in"
    static let launchAtLoginRefresh = "Refresh"
    static let launchAtLoginErrorPrefix = "Error:"
    static let refreshRate = "Sampling Frequency"
    static let hardwareConnection = "Hardware Bridge"
    static let hardwareConnected = "SMC Connected"
    static let hardwareDisconnected = "SMC Disconnected"
    static let retryConnection = "Reconnect Bridge"
    static let unknownConnectionError = "Unable to reach SMC service."
    static let quitApplication = "Quit Flux"
    static let noData = "No data available"
    static let openSystemHub = "Open Dashboard"
}

struct AppImages {
    static let rocket = "rocket"
    static let download = "arrow.down.circle"
    static let upload = "arrow.up.circle"
    static let diskRead = "internaldrive"
    static let diskWrite = "externaldrive"
    static let diskCapacity = "chart.pie"
    static let cpuUsage = "cpu"
    static let memory = "memorychip"
    static let fan = "fanblades"
    static let temperature = "thermometer.medium"
    static let gauge = "gauge.with.needle"
    static let checklist = "checklist"
    static let launchAtLogin = "person.badge.key"
    static let refresh = "arrow.clockwise"
    static let cpu = "processor"
    static let power = "power"
    static let window = "macwindow"
}
